export enum UserRole {
  ADMIN_GERAL = 'ADMIN_GERAL',
  ADMIN_INSTITUICAO = 'ADMIN_INSTITUICAO',
  GESTOR_PROJETO = 'GESTOR_PROJETO',
  FISCAL_PROJETO = 'FISCAL_PROJETO',
  CONSELHO_FISCAL_1 = 'CONSELHO_FISCAL_1',
  CONSELHO_FISCAL_2 = 'CONSELHO_FISCAL_2',
  CONSELHO_FISCAL_3 = 'CONSELHO_FISCAL_3',
  FISCAL_EXTERNO = 'FISCAL_EXTERNO',
}

export enum ProjectStatus {
  RASCUNHO = 'RASCUNHO',
  EM_ANALISE = 'EM_ANALISE',
  APROVADO = 'APROVADO',
  EM_EXECUCAO = 'EM_EXECUCAO',
  SUSPENSO = 'SUSPENSO',
  FINALIZADO = 'FINALIZADO',
  PRESTACAO_CONTAS = 'PRESTACAO_CONTAS',
  PRESTACAO_APROVADA = 'PRESTACAO_APROVADA',
  PRESTACAO_REPROVADA = 'PRESTACAO_REPROVADA',
}

export enum ExpenseStatus {
  PENDENTE = 'PENDENTE',
  APROVADO = 'APROVADO',
  PAGO = 'PAGO',
}

export enum DiligenceType {
  DOCUMENTAL = 'DOCUMENTAL',
  TECNICA = 'TECNICA',
  FINANCEIRA = 'FINANCEIRA',
}

export enum DiligenceStatus {
  ABERTA = 'ABERTA',
  RESPONDIDA = 'RESPONDIDA',
  FECHADA = 'FECHADA',
  VENCIDA = 'VENCIDA',
}

export enum GoalStatus {
  PENDENTE = 'Pendente',
  EM_ANDAMENTO = 'Em andamento',
  CONCLUIDA = 'Concluida',
}

export enum PriceResearchStatus {
  RASCUNHO = 'RASCUNHO',
  BUSCADA = 'BUSCADA',
  COM_RESULTADOS = 'COM_RESULTADOS',
  SEM_RESULTADOS = 'SEM_RESULTADOS',
  SELECIONADA = 'SELECIONADA',
  FINALIZADA = 'FINALIZADA',
  CANCELADA = 'CANCELADA',
}

export enum ReferenceType {
  MENOR = 'MENOR',
  MAIOR = 'MAIOR',
  MEDIA = 'MEDIA',
  MEDIANA = 'MEDIANA',
  MANUAL = 'MANUAL',
  ITEM = 'ITEM',
}

export enum SearchSource {
  PNCP = 'PNCP',
  RADAR_TCE_MT = 'RADAR_TCE_MT',
  MANUAL = 'MANUAL',
}

export enum DocumentCategory {
  JURIDICO = 'JURIDICO',
  PROJETO = 'PROJETO',
  RELATORIO = 'RELATORIO',
}

export enum AccountingReportStatus {
  PENDENTE = 'PENDENTE',
  APROVADA = 'APROVADA',
  REPROVADA = 'REPROVADA',
}
